version: '3'
services:
  db:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  
  api:
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/app
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    command: "yarn dev"